source 'https://supermarket.getchef.com'

metadata
cookbook 'application'
cookbook 'application_python'
cookbook 'application_nginx', git: 'git://github.com/poise/application_nginx.git', ref: '6339af0963139cb42946dec4111defd59502d064'
cookbook 'build-essential'
cookbook 'database'
cookbook 'firewall', git: 'git@github.com:osuosl-cookbooks/firewall'
cookbook 'geos'
cookbook 'git'
cookbook 'magic_shell'
cookbook 'osl-nginx', git: 'git@github.com:osuosl-cookbooks/osl-nginx'
cookbook 'postgis'
cookbook 'postgresql'
cookbook 'python'
cookbook 'selinux_policy'
cookbook 'yum-epel'
cookbook 'yum-ius'
cookbook 'yum-osuosl'
cookbook 'monitoring', git: 'git@github.com:osuosl-cookbooks/monitoring'
cookbook 'osl-munin', git: 'git@github.com:osuosl-cookbooks/osl-munin'
